FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
COPY packages/shared/package*.json ./packages/shared/
COPY packages/scheduler/package*.json ./packages/scheduler/
RUN npm ci --workspace=packages/shared --workspace=packages/scheduler
COPY packages/shared ./packages/shared
COPY packages/scheduler ./packages/scheduler
RUN npm run build --workspace=packages/shared --workspace=packages/scheduler

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/packages/shared ./packages/shared
COPY --from=builder /app/packages/scheduler ./packages/scheduler
COPY --from=builder /app/node_modules ./node_modules
CMD ["node", "packages/scheduler/dist/scheduler/src/index.js"]
