import { z } from 'zod';
declare const envSchema: z.ZodObject<{
    SUPABASE_URL: z.ZodString;
    SUPABASE_SERVICE_KEY: z.ZodString;
    DATABASE_URL: z.ZodString;
    WHATSAPP_PHONE_NUMBER_ID: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    WHATSAPP_ACCESS_TOKEN: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    WHATSAPP_VERIFY_TOKEN: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    WHATSAPP_BUSINESS_ACCOUNT_ID: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    OPENAI_API_KEY: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>;
    ANTHROPIC_API_KEY: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>;
    GEMINI_API_KEY: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>;
    LLM_PROVIDER: z.ZodDefault<z.ZodEnum<["openai", "anthropic", "gemini"]>>;
    LLM_MODEL: z.ZodDefault<z.ZodString>;
    EMBEDDING_PROVIDER: z.ZodDefault<z.ZodEnum<["openai", "gemini", "local"]>>;
    EMBEDDING_MODEL: z.ZodDefault<z.ZodString>;
    EMBEDDING_DIMENSIONS: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    WHISPER_PROVIDER: z.ZodDefault<z.ZodEnum<["openai", "local"]>>;
    WHISPER_MODEL: z.ZodDefault<z.ZodString>;
    RECORDINGS_DIR: z.ZodDefault<z.ZodString>;
    TEAMS_TENANT_ID: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>;
    TEAMS_CLIENT_ID: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>;
    TEAMS_CLIENT_SECRET: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>;
    TEAMS_USER_ID: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>;
    GROUP_ID: z.ZodDefault<z.ZodString>;
    ANSWER_SERVICE_PORT: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    SCHEDULER_PORT: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    INGESTION_PORT: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    ENABLE_DUPLICATE_DETECTION: z.ZodDefault<z.ZodString>;
    ENABLE_PROACTIVE_RECAP: z.ZodDefault<z.ZodString>;
    DIGEST_CRON: z.ZodDefault<z.ZodString>;
    SIMILARITY_THRESHOLD: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    LOW_CONFIDENCE_THRESHOLD: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
}, "strip", z.ZodTypeAny, {
    SUPABASE_URL: string;
    SUPABASE_SERVICE_KEY: string;
    DATABASE_URL: string;
    WHATSAPP_PHONE_NUMBER_ID: string;
    WHATSAPP_ACCESS_TOKEN: string;
    WHATSAPP_VERIFY_TOKEN: string;
    WHATSAPP_BUSINESS_ACCOUNT_ID: string;
    LLM_PROVIDER: "openai" | "anthropic" | "gemini";
    LLM_MODEL: string;
    EMBEDDING_PROVIDER: "openai" | "gemini" | "local";
    EMBEDDING_MODEL: string;
    EMBEDDING_DIMENSIONS: number;
    WHISPER_PROVIDER: "openai" | "local";
    WHISPER_MODEL: string;
    RECORDINGS_DIR: string;
    GROUP_ID: string;
    ANSWER_SERVICE_PORT: number;
    SCHEDULER_PORT: number;
    INGESTION_PORT: number;
    ENABLE_DUPLICATE_DETECTION: string;
    ENABLE_PROACTIVE_RECAP: string;
    DIGEST_CRON: string;
    SIMILARITY_THRESHOLD: number;
    LOW_CONFIDENCE_THRESHOLD: number;
    OPENAI_API_KEY?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    GEMINI_API_KEY?: string | undefined;
    TEAMS_TENANT_ID?: string | undefined;
    TEAMS_CLIENT_ID?: string | undefined;
    TEAMS_CLIENT_SECRET?: string | undefined;
    TEAMS_USER_ID?: string | undefined;
}, {
    SUPABASE_URL: string;
    SUPABASE_SERVICE_KEY: string;
    DATABASE_URL: string;
    WHATSAPP_PHONE_NUMBER_ID?: string | undefined;
    WHATSAPP_ACCESS_TOKEN?: string | undefined;
    WHATSAPP_VERIFY_TOKEN?: string | undefined;
    WHATSAPP_BUSINESS_ACCOUNT_ID?: string | undefined;
    OPENAI_API_KEY?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    GEMINI_API_KEY?: string | undefined;
    LLM_PROVIDER?: "openai" | "anthropic" | "gemini" | undefined;
    LLM_MODEL?: string | undefined;
    EMBEDDING_PROVIDER?: "openai" | "gemini" | "local" | undefined;
    EMBEDDING_MODEL?: string | undefined;
    EMBEDDING_DIMENSIONS?: string | undefined;
    WHISPER_PROVIDER?: "openai" | "local" | undefined;
    WHISPER_MODEL?: string | undefined;
    RECORDINGS_DIR?: string | undefined;
    TEAMS_TENANT_ID?: string | undefined;
    TEAMS_CLIENT_ID?: string | undefined;
    TEAMS_CLIENT_SECRET?: string | undefined;
    TEAMS_USER_ID?: string | undefined;
    GROUP_ID?: string | undefined;
    ANSWER_SERVICE_PORT?: string | undefined;
    SCHEDULER_PORT?: string | undefined;
    INGESTION_PORT?: string | undefined;
    ENABLE_DUPLICATE_DETECTION?: string | undefined;
    ENABLE_PROACTIVE_RECAP?: string | undefined;
    DIGEST_CRON?: string | undefined;
    SIMILARITY_THRESHOLD?: string | undefined;
    LOW_CONFIDENCE_THRESHOLD?: string | undefined;
}>;
export type Env = z.infer<typeof envSchema>;
export declare function getEnv(): Env;
export default getEnv;
